package john.client;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Tue Aug 14 16:21:21 BST 2007  
 */

public interface HelloWS extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://john/ws}logMessage   */

  public java.lang.String logMessage(java.lang.String message) throws java.rmi.RemoteException;
    public void logMessageAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String message) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://john/ws}samlHello   */

  public java.lang.String samlHello(java.lang.String name) throws java.rmi.RemoteException;
    public void samlHelloAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String name) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://john/ws}hello   */

  public java.lang.String hello(java.lang.String name) throws java.rmi.RemoteException;
    public void helloAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String name) throws java.rmi.RemoteException ;
       
  /**
   * Operation Name : {http://john/ws}longHello   */

  public java.lang.String longHello(java.lang.String name,int delay) throws java.rmi.RemoteException;
    public void longHelloAsync(weblogic.wsee.async.AsyncPreCallContext apc, java.lang.String name,int delay) throws java.rmi.RemoteException ;
  
}