<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="LogMessageWSServiceDefinitions" targetNamespace="http://john/ws" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/">
  <s0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://john/ws" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="logMessage">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="message" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </s0:types>
  <s0:message name="logMessage">
    <s0:part element="s1:logMessage" name="parameters"/>
  </s0:message>
  <s0:portType name="LogMessageWS">
    <s0:operation name="logMessage" parameterOrder="parameters">
      <s0:input message="s1:logMessage"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="LogMessageWSServiceSoapBinding" type="s1:LogMessageWS">
    <s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="logMessage">
      <s2:operation soapAction="" style="document"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
    </s0:operation>
  </s0:binding>
  <s0:service name="LogMessageWSService">
    <s0:port binding="s1:LogMessageWSServiceSoapBinding" name="LogMessageWSSoapPort">
      <s2:address location="http://localhost:7021/JohnWS/LogMessageWS"/>
    </s0:port>
  </s0:service>
</s0:definitions>