<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
  <con:wsdl><![CDATA[<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="JoeShopWSServiceDefinitions"
	targetNamespace="http://joe/ws/cart" xmlns=""
	xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
	xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
	xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/">
	<s0:types>
		<xs:schema attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="java:joe.ws.cart"
			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
			xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
			xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
			xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:complexType name="Invoice">
				<xs:sequence>
					<xs:element minOccurs="1" name="TotalPrice"
						nillable="false" type="xs:double" />
					<xs:element minOccurs="1" name="Client"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="AccountName"
						nillable="true" type="xs:string" />
					<xs:element maxOccurs="unbounded" minOccurs="0"
						name="Items" nillable="true" type="java:CartItem"
						xmlns:java="java:joe.ws.cart" />
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="CartItem">
				<xs:sequence>
					<xs:element minOccurs="1" name="Code"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Supplier"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Name"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Price"
						nillable="false" type="xs:double" />
					<xs:element minOccurs="1" name="Quantity"
						nillable="false" type="xs:int" />
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
		<xs:schema attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="john.ws.bank"
			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
			xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
			xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
			xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:element name="string" type="xs:string" />
		</xs:schema>
		<xs:schema attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="http://joe/ws/cart"
			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
			xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
			xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
			xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:import namespace="java:joe.ws.cart" />
			<xs:element name="confirmOrder">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="confirmOrderResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="java:Invoice"
							xmlns:java="java:joe.ws.cart" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getAllProducts">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="getAllProductsResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return"
							type="java:ArrayOfProductVO_literal" xmlns:java="java:john.db" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="newCart">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="client" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="newCartResponse">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="addItem">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="supplier" type="xs:string" />
						<xs:element name="code" type="xs:string" />
						<xs:element name="qty" type="xs:int" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="addItemResponse">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="setAccount">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="accountName" type="xs:string" />
						<xs:element name="accountPassword"
							type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="setAccountResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="xs:boolean" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="cancelOrder">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="cancelOrderResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getCart">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="getCartResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="java:Invoice"
							xmlns:java="java:joe.ws.cart" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="getClient">
				<xs:complexType>
					<xs:sequence />
				</xs:complexType>
			</xs:element>
			<xs:element name="getClientResponse">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="return" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:schema>
		<xs:schema attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="java:john.db"
			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
			xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
			xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
			xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:complexType name="ProductVO">
				<xs:sequence>
					<xs:element minOccurs="1" name="Description"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Price"
						nillable="false" type="xs:double" />
					<xs:element minOccurs="1" name="Name"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Supplier"
						nillable="true" type="xs:string" />
					<xs:element minOccurs="1" name="Code"
						nillable="true" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="ArrayOfProductVO_literal">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" minOccurs="0"
						name="ProductVO" nillable="true" type="java:ProductVO"
						xmlns:java="java:john.db" />
				</xs:sequence>
			</xs:complexType>
			<xs:element name="ArrayOfProductVO_literal"
				type="java:ArrayOfProductVO_literal" xmlns:java="java:john.db" />
		</xs:schema>
		<xs:schema attributeFormDefault="unqualified"
			elementFormDefault="qualified" targetNamespace="java:john.ws.bank"
			xmlns:s0="http://schemas.xmlsoap.org/wsdl/"
			xmlns:s1="http://joe/ws/cart" xmlns:s2="john.ws.bank"
			xmlns:s3="http://schemas.xmlsoap.org/wsdl/soap/"
			xmlns:s4="http://www.openuri.org/2002/04/wsdl/conversation/"
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
			<xs:complexType name="BankException" />
			<xs:element name="BankException" type="java:BankException"
				xmlns:java="java:john.ws.bank" />
		</xs:schema>
	</s0:types>
	<s0:message name="confirmOrder">
		<s0:part element="s1:confirmOrder" name="parameters" />
	</s0:message>
	<s0:message name="confirmOrderResponse">
		<s0:part element="s1:confirmOrderResponse" name="parameters" />
	</s0:message>
	<s0:message name="BankException">
		<s0:part element="s2:string" name="BankException" />
	</s0:message>
	<s0:message name="getAllProducts">
		<s0:part element="s1:getAllProducts" name="parameters" />
	</s0:message>
	<s0:message name="getAllProductsResponse">
		<s0:part element="s1:getAllProductsResponse" name="parameters" />
	</s0:message>
	<s0:message name="newCart">
		<s0:part element="s1:newCart" name="parameters" />
	</s0:message>
	<s0:message name="newCartResponse">
		<s0:part element="s1:newCartResponse" name="parameters" />
	</s0:message>
	<s0:message name="addItem">
		<s0:part element="s1:addItem" name="parameters" />
	</s0:message>
	<s0:message name="addItemResponse">
		<s0:part element="s1:addItemResponse" name="parameters" />
	</s0:message>
	<s0:message name="setAccount">
		<s0:part element="s1:setAccount" name="parameters" />
	</s0:message>
	<s0:message name="setAccountResponse">
		<s0:part element="s1:setAccountResponse" name="parameters" />
	</s0:message>
	<s0:message name="cancelOrder">
		<s0:part element="s1:cancelOrder" name="parameters" />
	</s0:message>
	<s0:message name="cancelOrderResponse">
		<s0:part element="s1:cancelOrderResponse" name="parameters" />
	</s0:message>
	<s0:message name="getCart">
		<s0:part element="s1:getCart" name="parameters" />
	</s0:message>
	<s0:message name="getCartResponse">
		<s0:part element="s1:getCartResponse" name="parameters" />
	</s0:message>
	<s0:message name="getClient">
		<s0:part element="s1:getClient" name="parameters" />
	</s0:message>
	<s0:message name="getClientResponse">
		<s0:part element="s1:getClientResponse" name="parameters" />
	</s0:message>
	<s0:portType name="JoeShopWS">
		<s0:operation name="confirmOrder" parameterOrder="parameters">
			<s0:input message="s1:confirmOrder" />
			<s0:output message="s1:confirmOrderResponse" />
			<s0:fault message="s1:BankException" name="BankException" />
		</s0:operation>
		<s0:operation name="getAllProducts"
			parameterOrder="parameters">
			<s0:input message="s1:getAllProducts" />
			<s0:output message="s1:getAllProductsResponse" />
		</s0:operation>
		<s0:operation name="newCart" parameterOrder="parameters">
			<s0:input message="s1:newCart" />
			<s0:output message="s1:newCartResponse" />
		</s0:operation>
		<s0:operation name="addItem" parameterOrder="parameters">
			<s0:input message="s1:addItem" />
			<s0:output message="s1:addItemResponse" />
		</s0:operation>
		<s0:operation name="setAccount" parameterOrder="parameters">
			<s0:input message="s1:setAccount" />
			<s0:output message="s1:setAccountResponse" />
		</s0:operation>
		<s0:operation name="cancelOrder" parameterOrder="parameters">
			<s0:input message="s1:cancelOrder" />
			<s0:output message="s1:cancelOrderResponse" />
		</s0:operation>
		<s0:operation name="getCart" parameterOrder="parameters">
			<s0:input message="s1:getCart" />
			<s0:output message="s1:getCartResponse" />
		</s0:operation>
		<s0:operation name="getClient" parameterOrder="parameters">
			<s0:input message="s1:getClient" />
			<s0:output message="s1:getClientResponse" />
		</s0:operation>
	</s0:portType>
	<s0:binding name="JoeShopWSServiceSoapBinding"
		type="s1:JoeShopWS">
		<s3:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<s0:operation name="confirmOrder">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="finish" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
			<s0:fault name="BankException">
				<s3:fault name="BankException" use="literal" />
			</s0:fault>
		</s0:operation>
		<s0:operation name="getAllProducts">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="continue" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="newCart">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="start" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="addItem">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="continue" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="setAccount">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="continue" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="cancelOrder">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="finish" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="getCart">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="continue" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
		</s0:operation>
		<s0:operation name="getClient">
			<s3:operation soapAction="" style="document" />
			<s4:transition phase="continue" />
			<s0:input>
				<s3:body parts="parameters" use="literal" />
			</s0:input>
			<s0:output>
				<s3:body parts="parameters" use="literal" />
			</s0:output>
		</s0:operation>
	</s0:binding>
	<s0:service name="JoeShopWSService">
		<s0:port binding="s1:JoeShopWSServiceSoapBinding"
			name="JoeShopWSSoapPort">
			<s3:address
				location="http://localhost:7041/JoeShopWS/JoeShopWS" />
		</s0:port>
	</s0:service>
</s0:definitions>]]></con:wsdl>
  <con:targetNamespace>http://joe/ws/cart</con:targetNamespace>
</con:wsdlEntry>