<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
  <con:wsdl><![CDATA[<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="HelloJmsWSServiceDefinitions" targetNamespace="http://john/ws" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/">
  <s0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://john/ws" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="hello">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="helloResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </s0:types>
  <s0:message name="hello">
    <s0:part element="s1:hello" name="parameters"/>
  </s0:message>
  <s0:message name="helloResponse">
    <s0:part element="s1:helloResponse" name="parameters"/>
  </s0:message>
  <s0:portType name="HelloJmsWS">
    <s0:operation name="hello" parameterOrder="parameters">
      <s0:input message="s1:hello"/>
      <s0:output message="s1:helloResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="HelloJmsWSServiceSoapBinding" type="s1:HelloJmsWS">
    <s2:binding style="document" transport="http://www.openuri.org/2002/04/soap/jms/"/>
    <s0:operation name="hello">
      <s2:operation soapAction="" style="document"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="HelloJmsWSService">
    <s0:port binding="s1:HelloJmsWSServiceSoapBinding" name="HelloJmsWSSoapPort">
      <s2:address location="jms://10.160.2.94:7041/JohnWS/HelloJmsWS?URI=jms.johnHelloQ&amp;FACTORY=javax.jms.QueueConnectionFactory"/>
    </s0:port>
  </s0:service>
</s0:definitions>]]></con:wsdl>
  <con:targetNamespace>http://john/ws</con:targetNamespace>
</con:wsdlEntry>