<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
  <con:wsdl><![CDATA[<?xml version='1.0' encoding='UTF-8'?>
<s0:definitions name="ShopWSServiceDefinitions" targetNamespace="http://john/ws/cart" xmlns="" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws/cart" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s3="http://www.openuri.org/2002/04/wsdl/conversation/">
  <s0:types>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="java:john.ws.cart" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws/cart" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s3="http://www.openuri.org/2002/04/wsdl/conversation/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:complexType name="CartItem">
        <xs:sequence>
          <xs:element minOccurs="1" name="Code" nillable="true" type="xs:string"/>
          <xs:element minOccurs="1" name="Name" nillable="true" type="xs:string"/>
          <xs:element minOccurs="1" name="Price" nillable="false" type="xs:double"/>
          <xs:element minOccurs="1" name="Quantity" nillable="false" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="Invoice">
        <xs:sequence>
          <xs:element minOccurs="1" name="TotalPrice" nillable="false" type="xs:double"/>
          <xs:element minOccurs="1" name="Client" nillable="true" type="xs:string"/>
          <xs:element minOccurs="1" name="CreditCardNumber" nillable="true" type="xs:string"/>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="Items" nillable="true" type="java:CartItem" xmlns:java="java:john.ws.cart"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="ArrayOfCartItem_literal">
        <xs:sequence>
          <xs:element maxOccurs="unbounded" minOccurs="0" name="CartItem" nillable="true" type="java:CartItem" xmlns:java="java:john.ws.cart"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCartItem_literal" type="java:ArrayOfCartItem_literal" xmlns:java="java:john.ws.cart"/>
    </xs:schema>
    <xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://john/ws/cart" xmlns:s0="http://schemas.xmlsoap.org/wsdl/" xmlns:s1="http://john/ws/cart" xmlns:s2="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s3="http://www.openuri.org/2002/04/wsdl/conversation/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="java:john.ws.cart"/>
      <xs:element name="newCart">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="client" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="newCartResponse">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="placeOrder">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="creditCardNumber" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="placeOrderResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="java:Invoice" xmlns:java="java:john.ws.cart"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="addItem">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="item" type="java:CartItem" xmlns:java="java:john.ws.cart"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="addItemResponse">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="getCart">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="getCartResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="java:ArrayOfCartItem_literal" xmlns:java="java:john.ws.cart"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="getClient">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="getClientResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="return" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
  </s0:types>
  <s0:message name="newCart">
    <s0:part element="s1:newCart" name="parameters"/>
  </s0:message>
  <s0:message name="newCartResponse">
    <s0:part element="s1:newCartResponse" name="parameters"/>
  </s0:message>
  <s0:message name="placeOrder">
    <s0:part element="s1:placeOrder" name="parameters"/>
  </s0:message>
  <s0:message name="placeOrderResponse">
    <s0:part element="s1:placeOrderResponse" name="parameters"/>
  </s0:message>
  <s0:message name="addItem">
    <s0:part element="s1:addItem" name="parameters"/>
  </s0:message>
  <s0:message name="addItemResponse">
    <s0:part element="s1:addItemResponse" name="parameters"/>
  </s0:message>
  <s0:message name="getCart">
    <s0:part element="s1:getCart" name="parameters"/>
  </s0:message>
  <s0:message name="getCartResponse">
    <s0:part element="s1:getCartResponse" name="parameters"/>
  </s0:message>
  <s0:message name="getClient">
    <s0:part element="s1:getClient" name="parameters"/>
  </s0:message>
  <s0:message name="getClientResponse">
    <s0:part element="s1:getClientResponse" name="parameters"/>
  </s0:message>
  <s0:portType name="ShopWS">
    <s0:operation name="newCart" parameterOrder="parameters">
      <s0:input message="s1:newCart"/>
      <s0:output message="s1:newCartResponse"/>
    </s0:operation>
    <s0:operation name="placeOrder" parameterOrder="parameters">
      <s0:input message="s1:placeOrder"/>
      <s0:output message="s1:placeOrderResponse"/>
    </s0:operation>
    <s0:operation name="addItem" parameterOrder="parameters">
      <s0:input message="s1:addItem"/>
      <s0:output message="s1:addItemResponse"/>
    </s0:operation>
    <s0:operation name="getCart" parameterOrder="parameters">
      <s0:input message="s1:getCart"/>
      <s0:output message="s1:getCartResponse"/>
    </s0:operation>
    <s0:operation name="getClient" parameterOrder="parameters">
      <s0:input message="s1:getClient"/>
      <s0:output message="s1:getClientResponse"/>
    </s0:operation>
  </s0:portType>
  <s0:binding name="ShopWSServiceSoapBinding" type="s1:ShopWS">
    <s2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <s0:operation name="newCart">
      <s2:operation soapAction="" style="document"/>
      <s3:transition phase="start"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body use="literal"/>
      </s0:output>
    </s0:operation>
    <s0:operation name="placeOrder">
      <s2:operation soapAction="" style="document"/>
      <s3:transition phase="finish"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
    <s0:operation name="addItem">
      <s2:operation soapAction="" style="document"/>
      <s3:transition phase="continue"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body use="literal"/>
      </s0:output>
    </s0:operation>
    <s0:operation name="getCart">
      <s2:operation soapAction="" style="document"/>
      <s3:transition phase="continue"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
    <s0:operation name="getClient">
      <s2:operation soapAction="" style="document"/>
      <s3:transition phase="continue"/>
      <s0:input>
        <s2:body parts="parameters" use="literal"/>
      </s0:input>
      <s0:output>
        <s2:body parts="parameters" use="literal"/>
      </s0:output>
    </s0:operation>
  </s0:binding>
  <s0:service name="ShopWSService">
    <s0:port binding="s1:ShopWSServiceSoapBinding" name="ShopWSSoapPort">
      <s2:address location="http://localhost:7041/JohnWS/ShopWS"/>
    </s0:port>
  </s0:service>
</s0:definitions>]]></con:wsdl>
  <con:targetNamespace>http://john/ws/cart</con:targetNamespace>
</con:wsdlEntry>